import { useState } from "react";

type Profile={id:string;auth_user_id:string;login_id:string;name:string;phone:string|null;role:string;is_active:boolean};

export default function DriverApp({profile,onLogout}:{profile:Profile;onLogout:()=>void}){
 const [darkMode,setDarkMode]=useState(true);const [soundOpen,setSoundOpen]=useState(false);const [historyOpen,setHistoryOpen]=useState(false);const [accountOpen,setAccountOpen]=useState(false);const [registerOpen,setRegisterOpen]=useState(false);const [workStatus,setWorkStatus]=useState("근무중");const [sound,setSound]=useState("alert_00001");
 const bg=darkMode?"#0f172a":"#f8fafc";const card=darkMode?"#1e293b":"#ffffff";const text=darkMode?"#f8fafc":"#0f172a";const muted=darkMode?"#94a3b8":"#64748b";
 return <div style={{minHeight:"100vh",background:bg,color:text,fontFamily:"Arial,sans-serif",padding:"12px",boxSizing:"border-box"}}>
  <header style={{textAlign:"center",padding:"8px 0 14px",fontWeight:900,fontSize:"19px"}}>🚖 기사 업무 시스템<div style={{fontSize:"11px",color:muted,marginTop:"5px"}}>꽃배달 실시간 배송 기사 전용</div></header>
  <div style={{display:"flex",justifyContent:"flex-end",gap:"6px",marginBottom:"10px"}}><button style={btn}>⚙️ 알림음</button><button style={btn} onClick={()=>setSoundOpen(true)}>🔔 설정</button><button style={btn} onClick={()=>setDarkMode(!darkMode)}>{darkMode?"☀️":"🌙"}</button><button style={logoutBtn} onClick={onLogout}>🚪 로그아웃</button></div>
  <section style={cardStyle(card)}><div style={titleStyle}>🚖 기사 업무 모드</div><div style={{lineHeight:1.9}}>👨 기사명 <b>{profile.name||profile.login_id}</b><br/>🪪 기사 ID <b>{profile.login_id}</b><br/>📞 연락처 <b>{profile.phone||"-"}</b><br/>🚚 근무상태 <span style={{background:workStatus==="근무중"?"#16a34a":"#64748b",color:"#fff",borderRadius:"20px",padding:"4px 9px",fontSize:"11px",fontWeight:800}}>{workStatus}</span></div><button style={wideBtn("#475569")} onClick={()=>setHistoryOpen(true)}>📜 배송완료 내역 조회</button><button style={wideBtn("#334155")} onClick={()=>setAccountOpen(true)}>👤 계정 관리</button></section>
  <div style={{display:"flex",gap:"8px",margin:"12px 0"}}><button style={workBtn("#10b981")} onClick={()=>setWorkStatus("근무중")}>출근하기</button><button style={workBtn("#dc2626")} onClick={()=>setWorkStatus("퇴근함")}>퇴근하기</button></div>
  <section style={cardStyle(card)}><div style={titleStyle}>📈 현재 오더 현황</div><div style={{display:"flex",textAlign:"center"}}><div style={{flex:1}}><div style={{fontSize:"11px",color:muted}}>미확인 오더</div><div style={{fontSize:"24px",fontWeight:900,color:"#38bdf8"}}>0</div></div><div style={{borderLeft:`1px solid ${darkMode?"#334155":"#e2e8f0"}`}}/><div style={{flex:1}}><div style={{fontSize:"11px",color:muted}}>진행중 오더</div><div style={{fontSize:"24px",fontWeight:900,color:"#f59e0b"}}>0</div></div></div></section>
  <section style={{marginTop:"14px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"8px",fontWeight:900}}>📦 나에게 배정된 오더<button style={{...btn,background:"#2563eb"}}>🔄 새로고침</button></div><div style={{...cardStyle(card),minHeight:"180px",display:"flex",alignItems:"center",justifyContent:"center",color:muted}}>현재 배정된 오더가 없습니다.</div></section>
  {accountOpen&&<Modal title="👤 계정 관리" close={()=>setAccountOpen(false)}><div style={{fontSize:"13px",color:muted,lineHeight:1.7}}>현재 로그인한 기사 계정<br/><b style={{color:text}}>{profile.login_id}</b></div><button style={wideBtn("#475569")} onClick={()=>setAccountOpen(false)}>비밀번호 변경</button><button style={wideBtn("#991b1b")} onClick={()=>setAccountOpen(false)}>회원탈퇴</button></Modal>}
  {historyOpen&&<Modal title="📜 배송완료 내역" close={()=>setHistoryOpen(false)}><div style={{padding:"25px 10px",textAlign:"center",color:muted}}>배송완료 내역이 없습니다.</div><button style={wideBtn("#475569")} onClick={()=>setHistoryOpen(false)}>닫기</button></Modal>}
  {soundOpen&&<Modal title="🔔 오더 알림음 설정" close={()=>setSoundOpen(false)}><select value={sound} onChange={e=>setSound(e.target.value)} style={input}>{Array.from({length:28},(_,i)=><option key={i} value={`alert_${String(i+1).padStart(5,"0")}`}>알림음 {i+1}</option>)}</select><button style={wideBtn("#2563eb")} onClick={()=>setSoundOpen(false)}>저장</button></Modal>}
  {registerOpen&&<Modal title="👤 기사 회원가입" close={()=>setRegisterOpen(false)}><input style={input} placeholder="기사 ID"/><input style={input} placeholder="이름"/><input style={input} placeholder="전화번호"/><input style={input} type="password" placeholder="비밀번호"/><button style={wideBtn("#16a34a")} onClick={()=>setRegisterOpen(false)}>회원가입</button></Modal>}
 </div>;
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div style={{position:"fixed",inset:0,zIndex:9999,background:"rgba(0,0,0,.72)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px",boxSizing:"border-box"}}><div style={{width:"100%",maxWidth:"380px",background:"#1e293b",borderRadius:"14px",padding:"18px",boxSizing:"border-box",color:"#fff",boxShadow:"0 15px 40px rgba(0,0,0,.4)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",fontWeight:900,fontSize:"17px",marginBottom:"16px"}}>{title}<button onClick={close} style={{border:0,background:"transparent",color:"#fff",fontSize:"24px"}}>×</button></div>{children}</div></div>}

const btn:React.CSSProperties={border:"1px solid #475569",borderRadius:"7px",background:"#1e293b",color:"#fff",padding:"8px 10px",fontSize:"11px",fontWeight:800,cursor:"pointer"};
const logoutBtn:React.CSSProperties={...btn,background:"#450a0a",borderColor:"#7f1d1d",color:"#fecaca"};
const cardStyle=(background:string):React.CSSProperties=>({background,border:"1px solid #334155",borderRadius:"12px",padding:"15px",boxSizing:"border-box",boxShadow:"0 4px 14px rgba(0,0,0,.2)"});
const titleStyle:React.CSSProperties={fontSize:"16px",fontWeight:900,marginBottom:"12px"};
const wideBtn=(background:string):React.CSSProperties=>({width:"100%",border:0,borderRadius:"7px",background,color:"#fff",padding:"11px",marginTop:"9px",fontWeight:800,cursor:"pointer"});
const workBtn=(background:string):React.CSSProperties=>({flex:1,border:0,borderRadius:"8px",background,color:"#fff",padding:"13px",fontWeight:900,cursor:"pointer"});
const input:React.CSSProperties={width:"100%",height:"44px",marginBottom:"10px",padding:"0 10px",boxSizing:"border-box",border:"1px solid #475569",borderRadius:"7px",background:"#0f172a",color:"#fff",outline:"none"};